<?php

namespace Database\Seeders;

use App\Models\Ingredient;
use Illuminate\Database\Seeder;

class IngredientSeeder extends Seeder
{
    public function run(): void
    {
        $ingredients = [
            // Zuivel (Dairy) - 25
            ['canonical_name' => 'Boter', 'category' => 'zuivel'],
            ['canonical_name' => 'Slagroom', 'category' => 'zuivel'],
            ['canonical_name' => 'Melk', 'category' => 'zuivel'],
            ['canonical_name' => 'Halfvolle melk', 'category' => 'zuivel'],
            ['canonical_name' => 'Karnemelk', 'category' => 'zuivel'],
            ['canonical_name' => 'Yoghurt', 'category' => 'zuivel'],
            ['canonical_name' => 'Griekse yoghurt', 'category' => 'zuivel'],
            ['canonical_name' => 'Kwark', 'category' => 'zuivel'],
            ['canonical_name' => 'Ricotta', 'category' => 'zuivel'],
            ['canonical_name' => 'Mozzarella', 'category' => 'zuivel'],
            ['canonical_name' => 'Cheddar', 'category' => 'zuivel'],
            ['canonical_name' => 'Gouda', 'category' => 'zuivel'],
            ['canonical_name' => 'Edammer', 'category' => 'zuivel'],
            ['canonical_name' => 'Camembert', 'category' => 'zuivel'],
            ['canonical_name' => 'Brie', 'category' => 'zuivel'],
            ['canonical_name' => 'Gorgonzola', 'category' => 'zuivel'],
            ['canonical_name' => 'Blauwe kaas', 'category' => 'zuivel'],
            ['canonical_name' => 'Parmezaan', 'category' => 'zuivel'],
            ['canonical_name' => 'Roomkaas', 'category' => 'zuivel'],
            ['canonical_name' => 'Hüttenkäse', 'category' => 'zuivel'],
            ['canonical_name' => 'Feta', 'category' => 'zuivel'],
            ['canonical_name' => 'Boursin', 'category' => 'zuivel'],
            ['canonical_name' => 'Rood kaas', 'category' => 'zuivel'],
            ['canonical_name' => 'Smeerkaas', 'category' => 'zuivel'],
            ['canonical_name' => 'Magere yoghurt', 'category' => 'zuivel'],
            ['canonical_name' => 'Ei', 'category' => 'zuivel'],

            // Groenten (Vegetables) - 30
            ['canonical_name' => 'Aardappel', 'category' => 'groenten'],
            ['canonical_name' => 'Uien', 'category' => 'groenten'],
            ['canonical_name' => 'Knoflook', 'category' => 'groenten'],
            ['canonical_name' => 'Wortelen', 'category' => 'groenten'],
            ['canonical_name' => 'Tomaat', 'category' => 'groenten'],
            ['canonical_name' => 'Paprika', 'category' => 'groenten'],
            ['canonical_name' => 'Komkommer', 'category' => 'groenten'],
            ['canonical_name' => 'Bloemkool', 'category' => 'groenten'],
            ['canonical_name' => 'Broccoli', 'category' => 'groenten'],
            ['canonical_name' => 'Spruiten', 'category' => 'groenten'],
            ['canonical_name' => 'Kool', 'category' => 'groenten'],
            ['canonical_name' => 'Witte kool', 'category' => 'groenten'],
            ['canonical_name' => 'Rode kool', 'category' => 'groenten'],
            ['canonical_name' => 'Prei', 'category' => 'groenten'],
            ['canonical_name' => 'Spinazie', 'category' => 'groenten'],
            ['canonical_name' => 'Slabonen', 'category' => 'groenten'],
            ['canonical_name' => 'Snijbonen', 'category' => 'groenten'],
            ['canonical_name' => 'Witte bonen', 'category' => 'groenten'],
            ['canonical_name' => 'Champignons', 'category' => 'groenten'],
            ['canonical_name' => 'Ossenhart', 'category' => 'groenten'],
            ['canonical_name' => 'Aubergine', 'category' => 'groenten'],
            ['canonical_name' => 'Courgette', 'category' => 'groenten'],
            ['canonical_name' => 'Sla', 'category' => 'groenten'],
            ['canonical_name' => 'Rucola', 'category' => 'groenten'],
            ['canonical_name' => 'Radijs', 'category' => 'groenten'],
            ['canonical_name' => 'Bieten', 'category' => 'groenten'],
            ['canonical_name' => 'Selderij', 'category' => 'groenten'],
            ['canonical_name' => 'Venkel', 'category' => 'groenten'],
            ['canonical_name' => 'Witloof', 'category' => 'groenten'],
            ['canonical_name' => 'Paksoi', 'category' => 'groenten'],
            ['canonical_name' => 'Knolraap', 'category' => 'groenten'],
            ['canonical_name' => 'Lente-ui', 'category' => 'groenten'],
            ['canonical_name' => 'Maïs', 'category' => 'groenten'],
            ['canonical_name' => 'Asperges', 'category' => 'groenten'],
            ['canonical_name' => 'Pastinaak', 'category' => 'groenten'],

            // Vlees (Meat) - 25
            ['canonical_name' => 'Rundvlees', 'category' => 'vlees'],
            ['canonical_name' => 'Varkensvlees', 'category' => 'vlees'],
            ['canonical_name' => 'Kippenvlees', 'category' => 'vlees'],
            ['canonical_name' => 'Varkensgehakt', 'category' => 'vlees'],
            ['canonical_name' => 'Rundgehakt', 'category' => 'vlees'],
            ['canonical_name' => 'Gemengd gehakt', 'category' => 'vlees'],
            ['canonical_name' => 'Kipengehakt', 'category' => 'vlees'],
            ['canonical_name' => 'Ham', 'category' => 'vlees'],
            ['canonical_name' => 'Spek', 'category' => 'vlees'],
            ['canonical_name' => 'Pancetta', 'category' => 'vlees'],
            ['canonical_name' => 'Worst', 'category' => 'vlees'],
            ['canonical_name' => 'Rookworst', 'category' => 'vlees'],
            ['canonical_name' => 'Gehakt worst', 'category' => 'vlees'],
            ['canonical_name' => 'Kalkoenvlees', 'category' => 'vlees'],
            ['canonical_name' => 'Eendvlees', 'category' => 'vlees'],
            ['canonical_name' => 'Lamsvlees', 'category' => 'vlees'],
            ['canonical_name' => 'Runder steak', 'category' => 'vlees'],
            ['canonical_name' => 'Kipfilet', 'category' => 'vlees'],
            ['canonical_name' => 'Kipbout', 'category' => 'vlees'],
            ['canonical_name' => 'Schnitzel', 'category' => 'vlees'],
            ['canonical_name' => 'Carbonade', 'category' => 'vlees'],
            ['canonical_name' => 'Varkensschnitzel', 'category' => 'vlees'],
            ['canonical_name' => 'Ossenstaart', 'category' => 'vlees'],
            ['canonical_name' => 'Runderribbetjes', 'category' => 'vlees'],
            ['canonical_name' => 'Kippenbouten', 'category' => 'vlees'],

            // Vis (Fish) - 20
            ['canonical_name' => 'Kabeljauw', 'category' => 'vis'],
            ['canonical_name' => 'Schol', 'category' => 'vis'],
            ['canonical_name' => 'Zeebaars', 'category' => 'vis'],
            ['canonical_name' => 'Zalm', 'category' => 'vis'],
            ['canonical_name' => 'Forel', 'category' => 'vis'],
            ['canonical_name' => 'Makreel', 'category' => 'vis'],
            ['canonical_name' => 'Haring', 'category' => 'vis'],
            ['canonical_name' => 'Paling', 'category' => 'vis'],
            ['canonical_name' => 'Tong', 'category' => 'vis'],
            ['canonical_name' => 'Heilbot', 'category' => 'vis'],
            ['canonical_name' => 'Mosselen', 'category' => 'vis'],
            ['canonical_name' => 'Oesters', 'category' => 'vis'],
            ['canonical_name' => 'Garnalen', 'category' => 'vis'],
            ['canonical_name' => 'Scampi', 'category' => 'vis'],
            ['canonical_name' => 'Inktvis', 'category' => 'vis'],
            ['canonical_name' => 'Pijlinktvis', 'category' => 'vis'],
            ['canonical_name' => 'Roodbaars', 'category' => 'vis'],
            ['canonical_name' => 'Seabream', 'category' => 'vis'],
            ['canonical_name' => 'Tarbot', 'category' => 'vis'],
            ['canonical_name' => 'Pladijs', 'category' => 'vis'],

            // Granen (Grains) - 20
            ['canonical_name' => 'Brood', 'category' => 'granen'],
            ['canonical_name' => 'Witbrood', 'category' => 'granen'],
            ['canonical_name' => 'Bruin brood', 'category' => 'granen'],
            ['canonical_name' => 'Volkorenbrood', 'category' => 'granen'],
            ['canonical_name' => 'Roggebrood', 'category' => 'granen'],
            ['canonical_name' => 'Sourdough', 'category' => 'granen'],
            ['canonical_name' => 'Ciabatta', 'category' => 'granen'],
            ['canonical_name' => 'Meergranenbrood', 'category' => 'granen'],
            ['canonical_name' => 'Rijst', 'category' => 'granen'],
            ['canonical_name' => 'Lange graanrijst', 'category' => 'granen'],
            ['canonical_name' => 'Ronde rijst', 'category' => 'granen'],
            ['canonical_name' => 'Arborio rijst', 'category' => 'granen'],
            ['canonical_name' => 'Paella rijst', 'category' => 'granen'],
            ['canonical_name' => 'Pasta', 'category' => 'granen'],
            ['canonical_name' => 'Spaghetti', 'category' => 'granen'],
            ['canonical_name' => 'Tagliatelle', 'category' => 'granen'],
            ['canonical_name' => 'Penne', 'category' => 'granen'],
            ['canonical_name' => 'Havermout', 'category' => 'granen'],
            ['canonical_name' => 'Gist', 'category' => 'granen'],
            ['canonical_name' => 'Bloem', 'category' => 'granen'],
            ['canonical_name' => 'Koek', 'category' => 'granen'],
            ['canonical_name' => 'Crackers', 'category' => 'granen'],

            // Kruiden (Herbs) - 15
            ['canonical_name' => 'Peterselie', 'category' => 'kruiden'],
            ['canonical_name' => 'Bieslook', 'category' => 'kruiden'],
            ['canonical_name' => 'Dille', 'category' => 'kruiden'],
            ['canonical_name' => 'Basilicum', 'category' => 'kruiden'],
            ['canonical_name' => 'Oregano', 'category' => 'kruiden'],
            ['canonical_name' => 'Thijm', 'category' => 'kruiden'],
            ['canonical_name' => 'Rozemarijn', 'category' => 'kruiden'],
            ['canonical_name' => 'Salie', 'category' => 'kruiden'],
            ['canonical_name' => 'Minze', 'category' => 'kruiden'],
            ['canonical_name' => 'Koriander blad', 'category' => 'kruiden'],
            ['canonical_name' => 'Tamme kervel', 'category' => 'kruiden'],
            ['canonical_name' => 'Munt', 'category' => 'kruiden'],
            ['canonical_name' => 'Laurier', 'category' => 'kruiden'],
            // Specerijen (Spices) - 20
            ['canonical_name' => 'Peper', 'category' => 'specerijen'],
            ['canonical_name' => 'Zwarte peper', 'category' => 'specerijen'],
            ['canonical_name' => 'Witte peper', 'category' => 'specerijen'],
            ['canonical_name' => 'Rode peper', 'category' => 'specerijen'],
            ['canonical_name' => 'Paprika poeder', 'category' => 'specerijen'],
            ['canonical_name' => 'Chilipeper', 'category' => 'specerijen'],
            ['canonical_name' => 'Cayenne peper', 'category' => 'specerijen'],
            ['canonical_name' => 'Nootmuskaat', 'category' => 'specerijen'],
            ['canonical_name' => 'Kaneel', 'category' => 'specerijen'],
            ['canonical_name' => 'Kruidnagel', 'category' => 'specerijen'],
            ['canonical_name' => 'Komijn', 'category' => 'specerijen'],
            ['canonical_name' => 'Korianderzaad', 'category' => 'specerijen'],
            ['canonical_name' => 'Gember', 'category' => 'specerijen'],
            ['canonical_name' => 'Vanille', 'category' => 'specerijen'],
            ['canonical_name' => 'Saffraanzaad', 'category' => 'specerijen'],
            ['canonical_name' => 'Venkelzaad', 'category' => 'specerijen'],

            // Peulvruchten (Legumes)
            ['canonical_name' => 'Linzen', 'category' => 'peulvruchten'],
            ['canonical_name' => 'Kikkererwten', 'category' => 'peulvruchten'],
            ['canonical_name' => 'Witte bonen', 'category' => 'peulvruchten'],
            ['canonical_name' => 'Rode bonen', 'category' => 'peulvruchten'],
            ['canonical_name' => 'Zwarte bonen', 'category' => 'peulvruchten'],
            ['canonical_name' => 'Bruine bonen', 'category' => 'peulvruchten'],
            ['canonical_name' => 'Erwten', 'category' => 'peulvruchten'],
            ['canonical_name' => 'Sojabonen', 'category' => 'peulvruchten'],

            // Fruit
            ['canonical_name' => 'Appel', 'category' => 'fruit'],
            ['canonical_name' => 'Peer', 'category' => 'fruit'],
            ['canonical_name' => 'Banaan', 'category' => 'fruit'],
            ['canonical_name' => 'Aardbei', 'category' => 'fruit'],
            ['canonical_name' => 'Bosbes', 'category' => 'fruit'],
            ['canonical_name' => 'Framboos', 'category' => 'fruit'],
            ['canonical_name' => 'Braam', 'category' => 'fruit'],
            ['canonical_name' => 'Zwarte bes', 'category' => 'fruit'],
            ['canonical_name' => 'Rode bes', 'category' => 'fruit'],
            ['canonical_name' => 'Kiwi', 'category' => 'fruit'],
            ['canonical_name' => 'Mango', 'category' => 'fruit'],
            ['canonical_name' => 'Ananas', 'category' => 'fruit'],
            ['canonical_name' => 'Sinaasappel', 'category' => 'fruit'],
            ['canonical_name' => 'Citroen', 'category' => 'fruit'],
            ['canonical_name' => 'Limoen', 'category' => 'fruit'],
            ['canonical_name' => 'Grapefruit', 'category' => 'fruit'],
            ['canonical_name' => 'Druif', 'category' => 'fruit'],
            ['canonical_name' => 'Abrikoos', 'category' => 'fruit'],
            ['canonical_name' => 'Pruim', 'category' => 'fruit'],
            ['canonical_name' => 'Avocado', 'category' => 'fruit'],

            // Sauzen (Sauces)
            ['canonical_name' => 'Olijfolie', 'category' => 'sauzen'],
            ['canonical_name' => 'Zonnebloemolie', 'category' => 'sauzen'],
            ['canonical_name' => 'Sesamolie', 'category' => 'sauzen'],
            ['canonical_name' => 'Azijn', 'category' => 'sauzen'],
            ['canonical_name' => 'Balsamico azijn', 'category' => 'sauzen'],
            ['canonical_name' => 'Rode wijnazijn', 'category' => 'sauzen'],
            ['canonical_name' => 'Appelazijn', 'category' => 'sauzen'],
            ['canonical_name' => 'Soja saus', 'category' => 'sauzen'],
            ['canonical_name' => 'Worcestersaus', 'category' => 'sauzen'],
            ['canonical_name' => 'Mosterd', 'category' => 'sauzen'],
            ['canonical_name' => 'Tomatenketsjup', 'category' => 'sauzen'],
            ['canonical_name' => 'Mayonaise', 'category' => 'sauzen'],
            ['canonical_name' => 'Sriracha', 'category' => 'sauzen'],
            ['canonical_name' => 'Tabasco saus', 'category' => 'sauzen'],
            ['canonical_name' => 'Honing', 'category' => 'sauzen'],
            ['canonical_name' => 'Jam', 'category' => 'sauzen'],
            ['canonical_name' => 'Pindakaas', 'category' => 'sauzen'],

            // Diepvries (Frozen)  
            ['canonical_name' => 'Diepvrieserwtjes', 'category' => 'diepvries'],
            ['canonical_name' => 'Diepvriesbonen', 'category' => 'diepvries'],
            ['canonical_name' => 'Diepvriesgroenten mengsel', 'category' => 'diepvries'],
            ['canonical_name' => 'Diepvriesspinaze', 'category' => 'diepvries'],
            ['canonical_name' => 'Diepvriesbrokkoli', 'category' => 'diepvries'],
            ['canonical_name' => 'Diepvriesbloemkool', 'category' => 'diepvries'],
            ['canonical_name' => 'Diepvriesfriet', 'category' => 'diepvries'],
            ['canonical_name' => 'Diepvriesgarnaaltjes', 'category' => 'diepvries'],
            ['canonical_name' => 'Diepvriesvisburger', 'category' => 'diepvries'],
            ['canonical_name' => 'Diepvriesfrikandel', 'category' => 'diepvries'],
            ['canonical_name' => 'Diepvriesaardbei', 'category' => 'diepvries'],

            // Blik (Canned)  
            ['canonical_name' => 'Blik tomatenpuree', 'category' => 'blik'],
            ['canonical_name' => 'Blik gehakte tomaten', 'category' => 'blik'],
            ['canonical_name' => 'Blik tomatensaus', 'category' => 'blik'],
            ['canonical_name' => 'Blik tonijn', 'category' => 'blik'],
            ['canonical_name' => 'Blik sardines', 'category' => 'blik'],
            ['canonical_name' => 'Blik makreel', 'category' => 'blik'],
            ['canonical_name' => 'Blik witte bonen', 'category' => 'blik'],
            ['canonical_name' => 'Blik rode bonen', 'category' => 'blik'],
            ['canonical_name' => 'Blik kikkererwten', 'category' => 'blik'],
            ['canonical_name' => 'Blik doperwten', 'category' => 'blik'],
            ['canonical_name' => 'Blik mais', 'category' => 'blik'],
            ['canonical_name' => 'Blik paprika', 'category' => 'blik'],
            ['canonical_name' => 'Blik champignons', 'category' => 'blik'],
            ['canonical_name' => 'Blik pijnboompitten', 'category' => 'blik'],
            ['canonical_name' => 'Blik kokosmelk', 'category' => 'blik'],

            // Dranken (Drinks)
            ['canonical_name' => 'Water', 'category' => 'dranken'],
            ['canonical_name' => 'Sinaasappelsap', 'category' => 'dranken'],
            ['canonical_name' => 'Appelsap', 'category' => 'dranken'],
            ['canonical_name' => 'Bier', 'category' => 'dranken'],
            ['canonical_name' => 'Blonde bier', 'category' => 'dranken'],
            ['canonical_name' => 'Bruin bier', 'category' => 'dranken'],
            ['canonical_name' => 'Rode wijn', 'category' => 'dranken'],
            ['canonical_name' => 'Witte wijn', 'category' => 'dranken'],
            ['canonical_name' => 'Rosé', 'category' => 'dranken'],
            ['canonical_name' => 'Champagne', 'category' => 'dranken'],
            ['canonical_name' => 'Bouillon runder', 'category' => 'dranken'],
            ['canonical_name' => 'Bouillon kip', 'category' => 'dranken'],
            ['canonical_name' => 'Bouillon groenten', 'category' => 'dranken'],
            ['canonical_name' => 'Bouillon vis', 'category' => 'dranken'],
        ];

        foreach ($ingredients as $ingredient) {
            Ingredient::firstOrCreate(
                ['canonical_name' => $ingredient['canonical_name']],
                ['category' => $ingredient['category']]
            );
        }
    }
}
